AWSTemplateFormatVersion: 2010-09-09
Description: Simple Private S3 Bucket for Terraform State

Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      Tags:
        - Key: Project
          Value: Terraform

Outputs:
  S3BucketName:
    Description: The name of the private S3 bucket
    Value: !Ref TerraformStateBucket
