aws_region      = "eu-west-1"
bucket_name     = "my-terraform-state"
github_repository = "Cindi-Ann/App-Test"
github_actions_role_name      = "github-actions-terraform"
terraform_policy_name         = "terraform-state-policy"
infrastructure_policy_name    = "infrastructure-policy"