aws_region      = "eu-west-1"
bucket_name     = "terraform-state-app-test-cindi"
github_repository = "Cindi-Ann/App-Test"
github_actions_role_name      = "github-actions-terraform"
terraform_policy_name         = "github-actions-terraform-state-policy"
infrastructure_policy_name    = "github-actions-infrastructure-policy"