name: Provision S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket-name:
        description: S3 bucket name
        required: true
        default: 'my-tf-bucket-cindi-test'
        type: string

jobs:
  provision-s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339713037108:role/gh-s3-role
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_bucket_name: "${{ github.event.inputs.bucket-name }}"
        run: |
          cd tf-s3-bucket/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
